// <auto-generated />
using AplicacionNETTBDEJ24.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AplicacionNETTBDEJ24.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240524232519_InitialPersistedGrantDbMigration")]
    partial class InitialPersistedGrantDbMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AplicacionNETTBDEJ24.Models.ClassEstudiante", b =>
                {
                    b.Property<int>("nualu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nualu"));

                    b.Property<int>("edad")
                        .HasColumnType("integer");

                    b.Property<string>("espe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("sem")
                        .HasColumnType("integer");

                    b.HasKey("nualu");

                    b.ToTable("ClassEstudiante");
                });
#pragma warning restore 612, 618
        }
    }
}
